spring:
  application:
    name: customer-service
  datasource:
    url: jdbc:mysql://localhost:3306/book_store
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8200
logging:
  level:
    org.springframework: DEBUG
